2025-03-31 10:32:46,750 - __main__ - INFO - Application started
2025-03-31 10:32:46,750 - __main__ - ERROR - Error occurred: division by zero
Traceback (most recent call last):
  File "/tmp/ipykernel_62832/4162642518.py", line 12, in <module>
    x = 3/0
ZeroDivisionError: division by zero
